### PR TITLE
Leave blocking section on callback while polling

### LINKED ISSUE #141: On MacOS, lablgtk2 runs OCaml code inside a blocking section, causing a crash in caml_memprof_handle_postponed_exn
Since recently, I am seeing my VeriFast application (using lablgtk2) crash sometimes on MacOS in `caml_memprof_handle_postponed_exn`. See https://github.com/verifast/verifast/issues/252 .

The chain of events is as follows:
- In `ml_poll` https://github.com/garrigue/lablgtk/blob/156973670a9c00b10f7f97201bbca054e6f3b66b/src/ml_glib.c#L303, lablgtk calls `caml_enter_blocking_section` and then calls the Gdk Quartz default `poll_func` https://gitlab.gnome.org/GNOME/gtk/-/blob/2.24.33/gdk/quartz/gdkeventloop-quartz.c#L709
- It calls AppKit's `nextEventMatchingMask` with the `NSDefaultRunLoopMode`.
- Apparently, in this mode, the run loop dispatches paint events. lablgtk (correctly, I think) does not expect this. The paint event is dispatched into OCaml code, which is not allowed inside a blocking section.

So, while I believe lablgtk is not "to blame" for this bug, any help or advice would of course be appreciated.

One (hacky) solution would be to add code to `marshal` to check if we are in a blocking section and, if so, temporarily exit it. Would that make sense?

I am curious as to why I am seeing these crashes only now. One recent change is that I recently switched from OCaml 4.6 to OCaml 4.13. Perhaps 4.13 is more sensitive to calling into OCaml while inside a blocking section?

### PR DESCRIPTION
**Pull request by btj**
Fixes #141

See also https://github.com/verifast/verifast/issues/252 . With this patch, the VeriFast IDE works correctly and I can no longer get it to crash.

### CODE REVIEW

**Comment by garrigue** [comment]
Interesting. This makes senses, but will have to be tested extensively, on Windows and Linux also.
Note that the function naming may be confusing, but `caml_enter_blocking_section` actually releases the ocaml global lock, and `caml_leave_blocking_section`, so this means that we may need to reacquire the lock when calling a callback into ML code.
This is a bit surprising, because I thought that callbacks were only occurring in places where we had already reacquired the lock. This may have been no longer the case with the switch to polling when using `GtkThread`.

**Comment by btj** [comment]
Dear @garrigue, your comments make me think that you did not carefully read the linked issue. The problem is that on MacOS, "polling" actually dispatches events.

**Comment by garrigue** [comment]
OK, now I understand.
The code was assuming that polling was just polling, checking for events without calling callbacks, and MacOS breaks that.
Note that windows is also pretty strange, not allowing you to do GUI operations in another thread, so that you have to queue them using the functions in GtkThread.
Just to be sure, on which architectures did you test your code?
I do not have much time for testing, and I'm afraid to merge this without at least testing on MacOS, Linux and Windows.

**Comment by btj** [comment]
I (briefly) tested VeriFast built using a lablgtk patched with this PR on Windows, Mac, and Linux. It worked fine. The patch is now in the VeriFast trunk (i.e. in the official nightly builds). Students will be using VeriFast over the course of this month to complete a homework, so additional testing will happen that way.

**Comment by garrigue** [comment]
Thank you. Testing, particularly on Windows, is always a major difficulty for this kind of problem, so this is very helpful.
I will merge this PR now. Tell me if any problem appears later on.

**Pull request merged**
