### PR TITLE
Add bindings for applying CSS from a string

### PR DESCRIPTION
**Pull request by btj**
My goal is to address https://github.com/coq/coq/issues/12779

### CODE REVIEW

**Comment by btj** [comment]
The code I want to push to coq is https://github.com/btj/coq/commit/56726ed657061586af75d13e84570c246ffe8f89

**Comment by btj** [comment]
@ejgallego @garrigue Any chance you could have a look at this? All users of CoqIDE on MacOS are experiencing a sluggish UI because of https://github.com/coq/coq/issues/12779 . This PR would enable a simple fix for that bug.

**Review by garrigue — APPROVED** [review]
Style is good, and there is a test example

**Comment by garrigue** [comment]
Sorry, the status of PRs is not always clear to me. This one was clearly ready to merge.

**Comment by btj** [comment]
Thanks! As soon as this lands in a release, I can submit https://github.com/btj/coq/commit/56726ed657061586af75d13e84570c246ffe8f89 as a Coq PR to fix https://github.com/coq/coq/issues/12779 .

**Pull request merged**
