### PR TITLE
More bindings

### PR DESCRIPTION
**Pull request by zoggy**

### CODE REVIEW

**Comment by garrigue** [comment]
Thanks. I definitely need to look into this soon.

**Comment by ejgallego** [comment]
Great, can you submit the dune fixes as a separate PR?

The bindings look fine to me, but I'll wait for Jacques feedback.

**Comment by garrigue** [comment]
I didn't check the details, but if you tell me it's ready, I'll merge it.

**Comment by zoggy** [comment]
I think it's ok.

**Comment by garrigue** [comment]
Sorry for the 2 year delay. I only did OCaml 5 compatiblity for a while...

**Pull request merged**
