### PR TITLE
[ci] Resurrect CI with Github actions.

### PR DESCRIPTION
**Pull request by ejgallego**

### CODE REVIEW

**Comment by ejgallego** [comment]
Seems like opam-depext is not working properly for win / osx.

**Comment by garrigue** [comment]
The extra dependency was added to the opam file.
It is mentioned in CHANGES.md (splitting of camlp-streams) but I forgot to add it to README.md.
I am yet to start understanding CI files.

**Comment by ejgallego** [comment]
Thanks; CI setup is pretty simple, however I am not sure why it depext is failing in OSX for example.

**Comment by ejgallego** [comment]
I think this is finally ready @garrigue , would you like to have a look?

**Comment by ejgallego** [comment]
Ok, merging this for now, problems in OSX / Win should be addressed by someone with the cycles on these platforms.

**Pull request merged**
