### PR TITLE
Cairo support for lablgtk3 (rough commit)

### PR DESCRIPTION
**Pull request by sacerdot**
============================================
This commit introduces an hard dependency on
cairo2 (aka ocaml-cairo) in order to reuse
the Cairo.context type.

With this commit it is already possible to use
cairo and pango (see examples/{cairo,pango1,pango2}.ml)

There are however some rough points:
1. all the config/Makefile/etc. have been patched with a
   quick&dirty solution and only tested under Linux.
   I assume we will switch to dune soon and thus this should
   be a temporary problem
2. the C code for lablgtk3 does NOT reuse the one of cairo.
   I am assuming the two C codes to be equivalent for now
3. I have not ported (yet?) the code of cairo2-gtk. Most of it
   uses deprecated Gdk functions that are no longer necessary.
   The only two remainings should be integrated into gdk.ml, but
   they are just two out of many many that were not bound before.
   I wonder if we could just implement the bindings on demand when
   old users ask for them.
============================================

Configuration/build files badly patched.
Please, somebody have a look at them.
However, if we eventually move to dune, it is
pointless to do that now.
- configure.in
- src/Makefile.in
- src/lablgtk3.in

Source code imported from ocaml-cairo:
- cairo_pango.ml
- cairo_pango.mli
- cairo_pango_stub.c

Changes to lablgtk3 code:
- gdk.ml{,i} (type cairo = Cairo.context)

New examples:
- cairo.ml
- pango1.ml
- pango2.ml

### CODE REVIEW

**Comment by sacerdot** [comment]
I have pushed Christophe's simplified code

**Comment by sacerdot** [comment]
I have pushed a solution to my issue #34 
I have made the nd.ml example to react to mouse motion/click events, something old widgets (e.g. GnomeCanvas) were able to do. That triggered issue #34 and the other recent commits in the pull request

**Comment by sacerdot** [comment]
@garrigue can you merge it now? I don't have more to commit for now.

Thanks for adding me. Can you do this merge though? Since it touches several things I prefer you to review the code (example excluded) before merging. Thanks in advance.

**Comment by garrigue** [comment]
Sorry for the delay. I have merged it now. I suppose that you disable `ocamlc.opt` because you are using `ocamlfind` ? I see no other way to do that.
I have just updated configure using my own aclocal, I see no problem otherwise at this point.
Do you need a release?

**Comment by sacerdot** [comment]
You are right, because of ocamlfind I had to disable direct use of ocamlc.opt.
Personally I don't need a release now. The ocamlgraph guys should try to port Dgraph to cairo, but I assume if they do they will work directly on git and thus probably they don't need it either at the moment.
I will now close #issue 6.

**Pull request merged**
