### PR TITLE
Typo in ml_gtk_text_buffer_get_iter_at_line_index

### PR DESCRIPTION
**Pull request by herbelin**
Hi, there seems to be a typo in the definition of `ml_gtk_text_buffer_get_iter_at_line_index` as its code refers to `gtk_text_buffer_get_iter_at_line_offset` (like in `ml_gtk_text_buffer_get_iter_at_line_offset`) while I guess `gtk_text_buffer_get_iter_at_line_index` is instead expected. I did not test the change, but we observed an utf8 issue in coqide which might be caused by this. Best, Hugo

### CODE REVIEW

**Comment by garrigue** [comment]
Indeed, this is a no-brainer. Thanks.

**Comment by herbelin** [comment]
@garrigue: what are your plans/policy for releases. Is there some chance that a new release including the fix is done before Coq releases its version 8.20, planned end of June?

**Comment by garrigue** [comment]
I can do that the week of June 10th. Now that OCaml 5.2 is released is a good timing for me too.

**Comment by herbelin** [comment]
That would be great! Thanks.

**Comment by garrigue** [comment]
@herbelin I have made a release last week. The opam package (https://github.com/ocaml/opam-repository/pull/26047) is in the pipeline, but I have no idea how long it will take.

**Pull request merged**
