### PR TITLE
[build] Split source code in terms of packages.

### PR DESCRIPTION
**Pull request by ejgallego**
We split code belonging to different packages to their own
directories.

This simplifies the dune build setup, and makes the code structure
easier to understand. It also makes `dune utop` work better.

We place tools a specific directory, and "orphaned" files in
`lablgtk3-unsupported`. I've orphaned the files not built by the
previous, explicit dune config, some of them could be brought back to
life I think.

Other than moving files around, this commit doesn't modify any code.

### CODE REVIEW

**Comment by garrigue** [comment]
The only concern is that it may make a bit hard to port changes between lablgtk2 and lablgtk3.
On the other hand, the two branches have already diverged to some extent.

**Comment by XVilka** [comment]
Will it be a part of the new beta or a release?

**Comment by ejgallego** [comment]
> Will it be a part of the new beta or a release?

I lean towards merging, it makes the code structure a bit easier for me, @garrigue ?

**Comment by garrigue** [comment]
If it helps you, I'm fine with it.
Still, is there a deep reason to rename src to lablgtk3 ?
It means that all files move around.
On the other hand, it may make the transition easier (just have to delete src by hand after).

**Comment by ejgallego** [comment]
> Still, is there a deep reason to rename src to lablgtk3 ?

Consistency, no problem in keeping `src` if you like that better. Let me know what you think.

> It means that all files move around.

Yup, tho at least my `git` tooling deals with renames pretty well so I was not very concerned with that too much.

> On the other hand, it may make the transition easier (just have to delete src by hand after).

**Comment by garrigue** [comment]
If the banking is not a problem, then I would suggest to replace all the `lablgtk3` prefixes in the directory names with `src`, this way we don't have to rename all the directories when we move to gtk4, if anybody is mad enough to try that.

**Comment by garrigue** [comment]
banking -> naming (the mysteries of smartphone input)

**Comment by XVilka** [comment]
Should be rebased, and probably merged since you all agree, why not?

**Comment by XVilka** [comment]
Any updates on this one?

**Comment by ejgallego** [comment]
I've updated this, however I didn't yet do the `lablgtk3 -> src` as some new thoughts came to my head.

> this way we don't have to rename all the directories when we move to gtk4, if anybody is mad enough to try that.

Indeed that's an option, but another alternative is for the current setup to support both `gtk3` and `gtk4` in the same tree; adding a `lablgtk4` directory would pose no problem.

But indeed I dunno, there are many options regarding code org.

With this setup renaming a directory is just a matter of doing `mv` and `dune` should pick the rest, so we can do that before mere.

**Comment by ejgallego** [comment]
Ping @garrigue

**Comment by garrigue** [comment]
What are you suggesting here? That we merge as is?
If you're still in doubt, I would prefer keeping src, but this is not essential.

**Comment by ejgallego** [comment]
> What are you suggesting here? That we merge as is?

I was wondering about 3 possible source code organizations:

- have directories that don't mention the gtk version, but keep separate repositories
- have directories that don't mention the gtk version, but keep separate branches [current situation]
- mention the gtk version, and have a single repos / branch

I'm unsure which one would be the best, for example now it seems not optimal for example due to issues, so that's a reason keeping the package name would make sense.

I've updated the PR to use option 1, note thus that I've dropped the `lablgtk3` prefix from the extra package name in favor of `src` so that is consistent.

**Comment by ejgallego** [comment]
> I've updated the PR to use option 1, note thus that I've dropped the `lablgtk3` prefix from the extra package name in favor of `src` so that is consistent.

For now I quite like the way it looks, so please feel free to merge if you agree on the current setup.

**Comment by garrigue** [comment]
Looks good to me too.

**Pull request merged**
