### PR TITLE
[build] Remove makefile support

### PR DESCRIPTION
**Pull request by ejgallego**
This is work in progress. OSX and Linux work fine, Windows is
pending, when done, this could be merged.

See https://discuss.ocaml.org/t/preferred-ocaml-windows-environments-mainly-for-continuous-integration/3299/3

We remove makefile support in favor of Dune, and also clean up some
outdated files.

TODO:

- should we add a debug profile to the Dune setup?
- windows build and testing
- what about the auto-init library?

### CODE REVIEW

**Comment by sacerdot** [comment]
Isn't lablgladecc3 build by dune? (I have not checked) It must be, it is used by applications to build (e.g. matita)

**Comment by ejgallego** [comment]
> Isn't lablgladecc3 build by dune? (I have not checked) It must be, it is used by applications to build (e.g. matita)

It was built on the gtk2 version of the dune patch, but not in gtk3 as I am not sure if it worked.

I will fix it right now, thanks for the feedback @sacerdot

**Comment by ejgallego** [comment]
@sacerdot should be fixed by https://github.com/garrigue/lablgtk/pull/41

**Comment by garrigue** [comment]
gdk_pixbuf_mlsource3 is needed too. It is actually the same as the one in lablgtk2, but we don't whether lablgtk2 is installed or not.

**Comment by ejgallego** [comment]
> gdk_pixbuf_mlsource3 is needed too. It is actually the same as the one in lablgtk2, but we don't whether lablgtk2 is installed or not.

It links to the library tho so it may not be so easy to share them. PR submitted, thanks!

**Comment by garrigue** [comment]
Also, lablgtk3 includes gtkspell support. I suppose it would need a separate package too, like gtksourceview. Currently it looks like it is not compiled.

**Comment by ejgallego** [comment]
> Also, lablgtk3 includes gtkspell support. I suppose it would need a separate package too, like gtksourceview. Currently it looks like it is not compiled.

Adding it, thanks!

**Comment by ejgallego** [comment]
We have confirmed the Windows dune build working more or less OK, so IMHO once we get the Windows CI ready we could consider this PR.

**Comment by XVilka** [comment]
Were there any updates regarding this conversion by the way?

**Comment by ejgallego** [comment]
@XVilka in Coq we are buidling lablgtk3 on windows and OSX using Dune without a problem, actually the only thing missing is for me to setup the Windows CI to merge this. If anyone could help that'd be great.

**Comment by ejgallego** [comment]
I guess it is time to merge this, as the makefile system is likely broken. We should tho open an issue about windows CI, for now Coq is building lablgtk3 with dune on win successfully, so it is just a matter of copying their setup.

**Comment by martindemello** [comment]
i think this also needs to fix #74

**Comment by garrigue** [comment]
Seeing issues such as #70, I agree that removing the Makefile from the release avoids confusion.
I let you @ejgallego go forward (just in case there are side effects...)

**Comment by XVilka** [comment]
It is also related to https://github.com/ocaml/ocaml-ci-scripts/issues/302

**Comment by ejgallego** [comment]
Indeed let's go forward, as of today the makefile is doing more harm than good, as it is basically not tested.

We need to add windows CI support tho, for now if there is a problem in Windows Coq's CI will complain tho as it builds lablgtk3 using Dune.

**Comment by ejgallego** [comment]
> I let you @ejgallego go forward (just in case there are side effects

Only missing bit as far as I do know is support for gtkdoc, I will open an issue about it, should not be very hard would someone want to tackle it.

> It is also related to [ocaml/ocaml-ci-scripts#302](https://github.com/ocaml/ocaml-ci-scripts/issues/302)

@XVilka indeed I have a branch that adds Azure support, however I would really like to try Travis again as it'd be so convenient to have only one CI provider. Let's discuss this in #52 anyways.

**Pull request merged**
