### PR TITLE
Fix several gtk3 examples, and remove some obsolete ones.

### PR DESCRIPTION
**Pull request by martindemello**

### CODE REVIEW

**Comment by garrigue** [comment]
Nice work.
I understand that you had to fix on your own, so I'm fine with the way you did it, but would it be possible to uniformise uses of `GMain` ?
Namely `GMain.init`, `GMain.quit` and `GMain.main` can be used directly, and there is no use to call them through submodules or through `GtkMain`. (I admit that I was not very uniform myself)

**Comment by martindemello** [comment]
hm, i think github won't let me resolve the merge conflict myself

**Comment by garrigue** [comment]
I'm going to see what I can do

**Comment by garrigue** [comment]
Thank you!

**Pull request merged**
