### PR TITLE
[opam] [dune-release] Fix opam metadata to reflect recent release.

### LINKED ISSUE #47: Convert README to Markdown
Maybe it makes sense also to modernize the README look for the first lablgtk3 release?

### PR DESCRIPTION
**Pull request by ejgallego**
After 3.0.beta4, the loose constraints should mostly work; depending
on the changes we do of course.

We also update the `homepage` field of the OPAM files, and the CHANGES
file, if I understand correctly this should indeed make `dune-release`
work out of the box [and to produce sensible changelogs]

Note that dune-release was incorrectly reading `CHANGES.API` to create
the OPAM changelog! So I had to fix that too.

### CODE REVIEW

**Comment by garrigue** [comment]
Any idea why the MacOS test fails?

**Comment by ejgallego** [comment]
CI is good here too [note this PR includes #49 ]

**Comment by garrigue** [comment]
This still fails on MacOS. Of course it works on my machine, but I'm using macports, not brew.
Quite mysterious.

**Comment by ejgallego** [comment]
This is a know bug in dune + brew @garrigue , nothing we can do here until they fix it upstream.

See the dune issue tracker if you need more info.

**Pull request merged**
