### PR TITLE
Add WRAP_WIDTH, WRAP_MODE tags to cell_properties_text, supported since gtk 2.8

### PR DESCRIPTION
**Pull request by nguermond**
Allow text wrapping in cells in tree view.

Description of wrap-width:
https://docs.gtk.org/gtk3/property.CellRendererText.wrap-width.html

I can't figure out how to get wrap-mode to work:
https://docs.gtk.org/gtk3/property.CellRendererText.wrap-mode.html

### CODE REVIEW

**Comment by garrigue** [comment]
Since it is there since 2.8, this should also probably go into lablgtk2.

**Comment by garrigue** [comment]
What is your problem with wrap-mode.
Since `pango_wrap_mode` is already defined, the conversions should be available.

**Comment by garrigue** [comment]
I see. You just need to add `WrapMode` in `propcc.ml4`, line 79:
```
  [ "Stretch"; "Style"; "Underline"; "Variant"; "EllipsizeMode"; "WrapMode" ];
```
Then run `make dev`.

**Comment by nguermond** [comment]
This seems to work!

**Comment by nguermond** [comment]
Should I make a similar pull request to `master`?

**Comment by garrigue** [comment]
> Should I make a similar pull request to `master`?

No need, I'll take care of this.

**Pull request merged**
