### PR TITLE
[build] Add missing C stub to build rules.

### LINKED ISSUE #53: gBuilder.cm* no longer distributed in beta4
Hi,

gBuilder.ml* is no longer compiled in beta4. Therefore the code generated by lablgladecc does not
work either.

Sorry for not having check before, I was on mission and I am just back.

### PR DESCRIPTION
**Pull request by ejgallego**
Fixes #53 for real. For some reason we where not testing this properly.

### CODE REVIEW

**Comment by garrigue** [comment]
I'm off for fine with the build fix, but I would prefer if you remove the stylistic changes to the examples. You just have to turn off -strict-srquence, like for other examples.

**Comment by ejgallego** [comment]
I will revert the changes to the examples.

Note tho that the warning is just not stylistic but alerts of potentially serious issues, even if in this case the warning is indeed, mostly harmless, disabling it in real code will tend to hide bugs, so it is not recommended (tho warning 5 in ocaml 4.08 got quite improved also and it helps).

**Comment by garrigue** [comment]
So we're now ready for beta5? This time `dune-release` should work?

**Comment by ejgallego** [comment]
> So we're now ready for beta5? This time `dune-release` should work?

Hopefully yes ...

**Comment by ejgallego** [comment]
It did on my tests :crossed_fingers:

**Pull request merged**
